
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/monitor?createDatabaseIfNotExist=true
    username: postgres
    password: London8793
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
    user: postgres
    password: London8793
  jpa:
    show-sql: true
    open-in-view: false